chore(move-mutator): improve single file err handling
Single files can be mutated only if the files require no deps
or address name resolving - in those cases we should printout
a proper error in the output.

An example:
```sh
move-spec-testing git:(chore/improve-error-handling) ✗ ./target/release/move-mutator -m move-mutator/tests/move-assets/simple/sources/Sum.move                                                                                                                                                                                   git:(chore/improve-error-handling|●5
error: address with no value
  ┌─ move-mutator/tests/move-assets/simple/sources/Sum.move:1:8
  │
1 │ module TestAccount::Sum {
  │        ^^^^^^^^^^^ address 'TestAccount' is not assigned a value. Try assigning it a value when calling the compiler

Error: AST generation failed
```